### ISSUE TITLE
Built in visualizer doesnt work

### ISSUE THREAD

**Issue by GorujoCY** [SafehouseCT/ClockWorld-for-Rainmeter#2]
Cant say that much about it unless asked however, it seems like when i installed this theme, the visaulizer doesnt work and it throws a playername= error in the log, ill copy paste this:
"Invalid PlayerName= (ClockWorld\Music Player\Visualizer\visualizer.ini - [MeasureState])"
im using spotify but originally playing it in the web browser. Is there a fix to this? 
I didnt try much but i tried digging around the configuration files in hopes to find a solution but nope, i should reinstall the vizualizer and update this post if it works and close the issue but as of now i just cant find a indication

Edit: seems like reinstalling worked however the vizualizer does not appear and no idication of error of sort so far

**Comment by stenakis** [comment]
Hello Gorujo-kun,
The issue you describe is known to me and I am currently trying to find a
solution for that. The error on the log does not actually indicate an error
on the skin. This is a left-over issue from the original skin that was
adjusted for Clockworld. As the bug is getting fixed try:
Hovering and unhovering the skin
Re-enabling the Visualizer from the Settings menu
Checking the SystemVariables.ini file (located in ***@***.***Resources)
folder) and confirm that the option "Music=NowPlaying.dll" is available
If none of the above works, try removing the visualizer.ini file from the
Clockworld directory (deleting it, or moving it to another folder) and
downloading the Monstercat visualizer on which Clockworld visualizer is
based.
The solution to this problem will most likely be available in the next
update.
Thank you, Evans

**Comment by GorujoCY** [comment]
Hello and thank your for reply.!
Perosnally im suprised you were aware of the issues as there's barely any issues in this repository. Anyways:
I cant seem to locate the skin so i cannot hover it
I renenabled the skin a few times and it didnt make a difference for me along with looking around to hover it, especially around near the player. 
I'll try installing the monstercat vizualizer then or wait for your patch to hopefully get it fixed 👍

**Comment by GorujoCY** [comment]
Update for this issue:
from what I understand, the equalizer built in to clockworld (or monstercat visualizer) seems to be able to detect stereo audio or specific audio drivers that can be heard by the applications in order to move (yes it has appeared, it seemed barely visible tho soo that's why), we dont know who to blame as there are many reasons that can cause it (most likely windows in my opinion) however ive been able to confirm it along with obs here. if anyone else can confirm the issue let me know.
im attaching a [video](https://cdn.discordapp.com/attachments/507254799603990529/836635303350501438/2021-04-27_19-02-12.mp4) here

from what it stands in the video, my bluetooth earphones in stereo mode make it work rather than having your laptop or pc or monitor's audio for example

**Comment by stenakis** [comment]
Visualizer can only detect sound from devices that are connected to the PC.
It can only detect frequencies from the speakers, headphones etc but not
from let's say Spotify on mobile devices or other wireless and
non-bluetooth devices. There is no way to adjust that, just because there
is no way to capture external audio from non-connected devices.
Thank you for the update, Evans
